name: Cross Compile

on:
  push:
    tags: ['v*']
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binary-suffix: ''
            artifact-name: <project-name>-linux
          - os: macos-latest
            binary-suffix: ''
            artifact-name: <project-name>-macos
          - os: windows-latest
            binary-suffix: '.exe'
            artifact-name: <project-name>-windows

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.4'
        cabal-version: '3.8'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}

    - name: Build dependencies
      run: cabal build --dependencies-only

    - name: Build
      run: cabal build

    - name: Copy binary
      run: |
        mkdir -p dist/
        cp $(cabal list-bin <project-name>)${{ matrix.binary-suffix }} dist/<project-name>${{ matrix.binary-suffix }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact-name }}
        path: dist/<project-name>${{ matrix.binary-suffix }}